### PR TITLE
Two new files added CheckEven.php and CheckOdd.php

### PR DESCRIPTION
**Pull request by vishalvnair124**
Two new files added CheckEven.php and CheckOdd.php.for checking the given integer is odd or even ,In CheckEven.php if the number is Even isEven function return true otherwise false. In CheckOdd.php if the number is Odd isOdd function return true otherwise false.

### CODE REVIEW

**Review by darwinz — APPROVED** [review]

**Review by darwinz — COMMENTED** [review]
Please add unit tests.  Thanks!

**Review by darwinz — CHANGES_REQUESTED** [review]
Add unit tests

**Comment by vishalvnair124** [comment]
I would like to ask a doubt.how do I add unit test in this

**Comment by darwinz** [comment]
If you look at PRs that have been closed/merged, there are quite a few examples of unit tests.  Here is one example:

https://github.com/TheAlgorithms/PHP/pull/153/files#diff-1c28e8aece542377d6125190ddb14a36b5889c18ab9897f7345cb8b89aa36f5f

**Pull request closed without merging**
