### PR TITLE
Linear Search | PHP

### PR DESCRIPTION
**Pull request by jowinjohnchemban**
#hacktoberfest

Reference: https://www.geeksforgeeks.org/linear-search/

### CODE REVIEW

**Comment by jowinjohnchemban** [comment]
Please #hacktoberfest-accepted

**Comment by jowinjohnchemban** [comment]
#22 
#hacktoberfest
#hacktoberfest-accepted
@

**Review by darwinz — CHANGES_REQUESTED** [review]
Please add docblocks and update `DIRECTORY.md`.  Also, add unit tests

**Review by jowinjohnchemban — COMMENTED** [review]
Updated to meet requirements and some debugging

**Review by jowinjohnchemban — COMMENTED** [review]
Updated

**Comment by jowinjohnchemban** [comment]
Added requested changes and some debugging

**Review by darwinz — APPROVED** [review]

**Review by jowinjohnchemban — COMMENTED** [review]
<?php

/**
 * Linear search in PHP
 * 
 * Reference: https://www.geeksforgeeks.org/linear-search/
 * 
 * @param Array $list a array of integers to search
 * @param integer $target an integer number to search for in the list
 * @return integer the index where the target is found (or -1 if not found)
 *
 *
 * USAGE: linear_search(ARRAY,INTEGER);
 * 
 * OUTPUT: 0        - If not found
 *         POSITION - If found
 *
 * Examples:
 * 
 *  linear_search([5, 7, 8, 11, 12, 15, 17, 18, 20], 15)
 *  6
 *  
 *  linear_search([5, 7, 8, 11, 12, 15, 17, 18, 20], 1)
 *  0
 * 
 **/


function linear_search($list, $target) #Linear Search
  { $n = sizeof($list);
    for($i = 0; $i < $n; $i++) 
    { 
        if($list[$i] == $target)
                {
                  return ($i+1); #FOUND
                }
    } 
    return 0;  # NOT FOUND
   }



# DRIVER CODE  

echo linear_search([5, 7, 8, 11, 12, 15, 17, 18, 20], 15); # OUTPUT DISPLAY | TRUE
echo linear_search([5, 7, 8, 11, 12, 15, 17, 18, 20], 1);  # OUTPUT DISPLAY | FALSE

?>

**Pull request merged**
